# Generated by Django 6.0.3 on 2026-03-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='created_by',
        ),
    ]
