# Generated by Django 6.0.3 on 2026-03-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_location_company_name_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number_of_workers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
